version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: freedomcenter_postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  nest-app:
    build: .
    container_name: freedomcenter_app
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  pgdata:
